export const getCountryCode = (countryName: string): string => {
  const mapping: Record<string, string> = {
    'United States': 'US',
    'USA': 'US',
    'United Kingdom': 'GB',
    'UK': 'GB',
    'Canada': 'CA',
    'France': 'FR',
    'Germany': 'DE',
    'Netherlands': 'NL',
    'Spain': 'ES',
    'Italy': 'IT',
    'Sweden': 'SE',
    'Denmark': 'DK',
    'Finland': 'FI',
    'Poland': 'PL',
    'Russia': 'RU',
    'Ukraine': 'UA',
    'Australia': 'AU',
    'Belgium': 'BE',
    'Austria': 'AT',
    'Switzerland': 'CH',
    'Portugal': 'PT',
    'Romania': 'RO',
    'Croatia': 'HR',
    'Estonia': 'EE',
    'Latvia': 'LV',
    'Lithuania': 'LT',
    'Czech Republic': 'CZ',
    'Slovakia': 'SK',
    'Hungary': 'HU',
    'Bulgaria': 'BG',
    'Greece': 'GR',
    'Ireland': 'IE',
    'Norway': 'NO',
    'Japan': 'JP',
    'South Korea': 'KR',
    'China': 'CN',
    'India': 'IN',
    'Brazil': 'BR',
    'Mexico': 'MX',
    'Argentina': 'AR',
    'South Africa': 'ZA',
    'Nigeria': 'NG',
    'Egypt': 'EG',
    'Israel': 'IL',
    'Turkey': 'TR',
    'Saudi Arabia': 'SA',
    'United Arab Emirates': 'AE',
    'Indonesia': 'ID',
    'Malaysia': 'MY',
    'Singapore': 'SG',
    'Thailand': 'TH',
    'Vietnam': 'VN',
    'Philippines': 'PH',
    'New Zealand': 'NZ',
    'Chile': 'CL',
    'Colombia': 'CO',
    'Peru': 'PE',
    'Venezuela': 'VE',
  };

  return mapping[countryName] || 'UN'; // UN for unknown
};
